#!/bin/sh

alias ls="exa --group-directories-first"
alias lsal="exa --group-directories-first -al"
alias ll="exa --group-directories-first -al"
alias tree="exa --tree"
alias grep="grep --color=auto"
alias wget="wget --hsts-file=\"$XDG_DATA_HOME/wget-hsts\""

alias free="free -h"
alias df="df -h"

alias ..="cd .."
alias ...="cd ../.."
alias /="cd /"
alias -- -="cd -"

alias pQ="paru -Q"
alias pS="paru -S"
alias pR="paru -R"

alias pQi="paru -Qi"
alias pQl="paru -Ql"
alias pQs="paru -Qs"
alias pSi="paru -Si"
alias pSs="paru -Ss"

alias v=nvim
alias sv="sudo nvim"
alias c="tty-clock -tc"
alias cb="xclip -selection clipboard"

alias config="git --git-dir=$HOME/.git --work-tree=$HOME"
