#!/bin/sh

tw () {
	channel="$1"
	case "$2" in
		1) quality=720p60 ;;
		2) quality=480p   ;;
		*) quality=best   ;;
	esac
	streamlink "https://twitch.tv/$channel" "$quality" & disown
}
alias twq="brave \"https://isedol.xyz\" &"
alias tww="tw woowakgood"
alias twi="tw vo_ine"
alias twj="tw jingburger"
alias twl="tw lilpaaaaaa"
alias twr="tw cotton__123"
alias twg="tw gosegugosegu"
alias twv="tw viichan6"
alias tw1="tw 111roentgenium"
alias twc="tw chunyangkr"
