#!/bin/sh


### DAEMONS ###

# compositor
#picom -b --animations --animation-for-open-window zoom --animation-stiffness 25 &

# rendering
systemctl --user start xsettingsd &

# emacs
emacs --daemon &

# storage
udiskie &

# notification
dunst &

# hangul
nimf &


### COMMANDS ###

# touchpad
xinput set-prop "SYNA309F:00 06CB:CD0B Touchpad" "libinput Tapping Enabled" 1 &

# background image
feh --no-fehbg --bg-fill --randomize ~/.wallpapers/* &

# tear-free
xrandr --output eDP --set TearFree on &

# mouse pointer
xsetroot -cursor_name left_ptr &

# repeat rate
xset r rate 250 30 &

# alert
batteryalert &

# numlock
numlockx on &
