#!/bin/sh

sxhkd &      # keybind
bspswallow & # swallow

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap   0
bspc config split_ratio  0.5

bspc config normal_border_color  "#000000"
bspc config active_border_color  "#808080"
bspc config focused_border_color "#FFFFFF"

bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Emacs state=tiled
