#!/bin/sh

sxhkd &

bspc monitor -d I II III "III I" "III II" "III III" "III III I" "III III II" "III III III" O

bspc config border_width 0
bspc config window_gap   0
bspc config split_ratio  0.5

bspc config normal_border_color  "#000000"
bspc config active_border_color  "#808080"
bspc config focused_border_color "#FFFFFF"

bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Emacs state=tiled
